export const CREATE_DELIVERY_METHOD = "CREATE_DELIVERY_METHOD";
export const DELETE_DELIVERY_METHOD = "DELETE_DELIVERY_METHOD";
export const SET_DELIVERY_METHOD = "SET_DELIVERY_METHOD";
export const SET_DELIVERY_METHODS = "SET_DELIVERY_METHODS";
export const UPDATE_DELIVERY_METHOD = "UPDATE_DELIVERY_METHOD";