
export const DELETE_SALE_RECORD_DETAIL = "DELETE_SALE_RECORD_DETAIL";
export const SET_SALE_RECORD_DETAIL = "SET_SALE_RECORD_DETAIL";
export const ADD_SALE_RECORD_DETAIL = "ADD_SALE_RECORD_DETAIL";
export const REMOVE_SALE_RECORD_DETAIL = "REMOVE_SALE_RECORD_DETAIL";
export const UPDATE_SALE_RECORD_DETAIL = "UPDATE_SALE_RECORD_DETAIL";
export const SET_PRODUCT_OPTIONS = "SET_PRODUCT_OPTIONS";